language: python
python:
  - "3.7"
services:
  - elasticsearch
  - redis
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=. -m unittest
after_success:
  - coveralls