#!/bin/bash

# Download and install Logstash
# Check http://www.elastic.co/downloads/logstash for latest version and replace link
# Only download the file if it doesn't already exist
if [ ! -f logstash-6.1.1.deb ]; then
    curl -L -O https://artifacts.elastic.co/downloads/logstash/logstash-6.1.1.deb
fi
# Install deb
sudo dpkg -i logstash-6.1.1.deb

echo Giving permissions to Logstash
# Give permissions (https://discuss.elastic.co/t/i-cannot-start-logstash-on-my-machine-error-message-inside/88900)
sudo chown -R logstash.logstash /usr/share/logstash
sudo chmod -R 777 /usr/share/logstash/data
sudo chown -R logstash.logstash /etc/default/logstash
