from datauploader.uploader.datafile import DataFile


class GeneralFile(DataFile):
    """ Class that represents a general file. """

    def __init__(self, datafile):
        DataFile.__init__(self, datafile)
        self.fieldnames = ['date', 'dayType', 'version', 'expeditionNumber', 'minExpeditionTime', 'maxExpeditionTime',
                           'averageExpeditionTime', 'licensePlateNumber', 'GPSPointsNumber',
                           'averageTimeBetweenGPSPoints', 'GPSNumberWithRoute', 'GPSNumberWithoutRoute',
                           'transactionNumber', 'transactionOnBusNumber', 'transactionOnMetroNumber',
                           'transactionOnTrainNumber', 'transactionOnBusStation', 'smartcardNumber',
                           'transactionWithRoute', 'transactionWithoutRoute', 'stagesWithBusAlighting',
                           'stagesWithMetroAlighting', 'stagesWithTrainAlighting', 'stagesWithBusStationAlighting',
                           'tripNumber', 'tripsWithOneStage', 'tripsWithTwoStages', 'tripsWithThreeStages',
                           'tripsWithFourStages', 'tripsWithFiveOrMoreStages', 'tripsWithOnlyMetro',
                           'tripsThatUseMetro', 'tripsWithoutLastAlighting', 'averageTimeOfTrips',
                           'averageDistanceOfTrips', 'averageVelocityOfTrips', 'tripNumberInMorningRushHour',
                           'averageTimeInMorningRushTrips', 'averageDistanceInMorningRushTrips',
                           'averageVelocityInMorningRushTrips', 'tripNumberInAfternoonRushHour',
                           'averageTimeInAfternoonRushTrips', 'averageDistanceInAfternoonRushTrips',
                           'averageVelocityInAfternoonRushTrips', "transactionInMorningRushHour",
                           "transactionInAfternoonRushHour", "alightingNumber", "alightingNumberInMorningRushHour",
                           "alightingNumberInAfternoonRushHour", "stopsNumberWithTypeE", "stopsNumberWithTypeT",
                           "stopsNumberWithTypeL", "stopsNumberWithTypeI", "transactionNumberInStopsWithTypeE",
                           "transactionNumberInStopsWithTypeT", "transactionNumberInStopsWithTypeL",
                           "transactionNumberInStopsWithTypeI", "firstStopWithMoreValidations",
                           "secondStopWithMoreValidations", "thirdStopWithMoreValidations",
                           "fourthStopWithMoreValidations", "fifthStopWithMoreValidations",
                           "sixthStopWithMoreValidations", "seventhStopWithMoreValidations",
                           "eighthStopWithMoreValidations", "ninethStopWithMoreValidations",
                           "tenthStopWithMoreValidations", "transactionNumberInFirstStopWithMoreValidations",
                           "transactionNumberInSecondStopWithMoreValidations",
                           "transactionNumberInThirdStopWithMoreValidations",
                           "transactionNumberInFourthStopWithMoreValidations",
                           "transactionNumberInFifthStopWithMoreValidations",
                           "transactionNumberInSixthStopWithMoreValidations",
                           "transactionNumberInSeventhStopWithMoreValidations",
                           "transactionNumberInEighthStopWithMoreValidations",
                           "transactionNumberInNinethStopWithMoreValidations",
                           "transactionNumberInTenthStopWithMoreValidations", "firstBusStopWithMoreValidations",
                           "secondBusStopWithMoreValidations", "thirdBusStopWithMoreValidations",
                           "fourthBusStopWithMoreValidations", "fifthBusStopWithMoreValidations",
                           "sixthBusStopWithMoreValidations", "seventhBusStopWithMoreValidations",
                           "eighthBusStopWithMoreValidations", "ninethBusStopWithMoreValidations",
                           "tenthBusStopWithMoreValidations", "transactionNumberInFirstBusStopWithMoreValidations",
                           "transactionNumberInSecondBusStopWithMoreValidations",
                           "transactionNumberInThirdBusStopWithMoreValidations",
                           "transactionNumberInFourthBusStopWithMoreValidations",
                           "transactionNumberInFifthBusStopWithMoreValidations",
                           "transactionNumberInSixthBusStopWithMoreValidations",
                           "transactionNumberInSeventhBusStopWithMoreValidations",
                           "transactionNumberInEighthBusStopWithMoreValidations",
                           "transactionNumberInNinethBusStopWithMoreValidations",
                           "transactionNumberInTenthBusStopWithMoreValidations"]

    def row_parser(self, row, path, timestamp):
        return {
            "path": path,
            "timestamp": timestamp,
            "date": row['date'],
            "dayType": row['dayType'],
            "version": row['version'],
            "expeditionNumber": int(row['expeditionNumber']),
            "minExpeditionTime": float(row['minExpeditionTime']),
            "maxExpeditionTime": float(row['maxExpeditionTime']),
            "averageExpeditionTime": float(row['averageExpeditionTime']),
            "licensePlateNumber": int(row['licensePlateNumber']),
            "GPSPointsNumber": int(row['GPSPointsNumber']),
            "averageTimeBetweenGPSPoints": float(row['averageTimeBetweenGPSPoints']),
            "GPSNumberWithRoute": int(row['GPSNumberWithRoute']),
            "GPSNumberWithoutRoute": int(row['GPSNumberWithoutRoute']),
            "transactionNumber": int(row['transactionNumber']),
            "transactionOnBusNumber": float(row['transactionOnBusNumber']),
            "transactionOnMetroNumber": float(row['transactionOnMetroNumber']),
            "transactionOnTrainNumber": float(row['transactionOnTrainNumber']),
            "transactionOnBusStation": float(row['transactionOnBusStation']),
            "smartcardNumber": int(row['smartcardNumber']),
            "transactionWithRoute": int(row['transactionWithRoute']),
            "transactionWithoutRoute": int(row['transactionWithoutRoute']),
            "stagesWithBusAlighting": float(row['stagesWithBusAlighting']),
            "stagesWithMetroAlighting": float(row['stagesWithMetroAlighting']),
            "stagesWithTrainAlighting": float(row['stagesWithTrainAlighting']),
            "stagesWithBusStationAlighting": float(row['stagesWithBusStationAlighting']),
            "tripNumber": int(row['tripNumber']),
            "tripsWithOneStage": float(row['tripsWithOneStage']),
            "tripsWithTwoStages": float(row['tripsWithTwoStages']),
            "tripsWithThreeStages": float(row['tripsWithThreeStages']),
            "tripsWithFourStages": float(row['tripsWithFourStages']),
            "tripsWithFiveOrMoreStages": float(row['tripsWithFiveOrMoreStages']),
            "tripsWithOnlyMetro": float(row['tripsWithOnlyMetro']),
            "tripsThatUseMetro": float(row['tripsThatUseMetro']),
            "tripsWithoutLastAlighting": float(row['tripsWithoutLastAlighting']),
            "averageTimeOfTrips": float(row['averageTimeOfTrips']),
            "averageDistanceOfTrips": float(row['averageDistanceOfTrips']),
            "averageVelocityOfTrips": float(row['averageVelocityOfTrips']),
            "tripNumberInMorningRushHour": float(row['tripNumberInMorningRushHour']),
            "averageTimeInMorningRushTrips": float(row['averageTimeInMorningRushTrips']),
            "averageDistanceInMorningRushTrips": float(row['averageDistanceInMorningRushTrips']),
            "averageVelocityInMorningRushTrips": float(row['averageVelocityInMorningRushTrips']),
            "tripNumberInAfternoonRushHour": float(row['tripNumberInAfternoonRushHour']),
            "averageTimeInAfternoonRushTrips": float(row['averageTimeInAfternoonRushTrips']),
            "averageDistanceInAfternoonRushTrips": float(row['averageDistanceInAfternoonRushTrips']),
            "averageVelocityInAfternoonRushTrips": float(row['averageVelocityInAfternoonRushTrips']),
            "transactionInMorningRushHour": float(row['transactionInMorningRushHour']),
            "transactionInAfternoonRushHour": float(row['transactionInAfternoonRushHour']),
            "alightingNumber": float(row['alightingNumber']),
            "alightingNumberInMorningRushHour": float(row['alightingNumberInMorningRushHour']),
            "alightingNumberInAfternoonRushHour": float(row['alightingNumberInAfternoonRushHour']),
            "stopsNumberWithTypeE": float(row['stopsNumberWithTypeE']),
            "stopsNumberWithTypeT": float(row['stopsNumberWithTypeT']),
            "stopsNumberWithTypeL": float(row['stopsNumberWithTypeL']),
            "stopsNumberWithTypeI": float(row['stopsNumberWithTypeI']),
            "transactionNumberInStopsWithTypeE": float(row['transactionNumberInStopsWithTypeE']),
            "transactionNumberInStopsWithTypeT": float(row['transactionNumberInStopsWithTypeT']),
            "transactionNumberInStopsWithTypeL": float(row['transactionNumberInStopsWithTypeL']),
            "transactionNumberInStopsWithTypeI": float(row['transactionNumberInStopsWithTypeI']),
            "firstStopWithMoreValidations": row['firstStopWithMoreValidations'],
            "secondStopWithMoreValidations": row['secondStopWithMoreValidations'],
            "thirdStopWithMoreValidations": row['thirdStopWithMoreValidations'],
            "fourthStopWithMoreValidations": row['fourthStopWithMoreValidations'],
            "fifthStopWithMoreValidations": row['fifthStopWithMoreValidations'],
            "sixthStopWithMoreValidations": row['sixthStopWithMoreValidations'],
            "seventhStopWithMoreValidations": row['seventhStopWithMoreValidations'],
            "eighthStopWithMoreValidations": row['eighthStopWithMoreValidations'],
            "ninethStopWithMoreValidations": row['ninethStopWithMoreValidations'],
            "tenthStopWithMoreValidations": row['tenthStopWithMoreValidations'],
            "transactionNumberInFirstStopWithMoreValidations": float(
                row['transactionNumberInFirstStopWithMoreValidations']),
            "transactionNumberInSecondStopWithMoreValidations": float(
                row['transactionNumberInSecondStopWithMoreValidations']),
            "transactionNumberInThirdStopWithMoreValidations": float(
                row['transactionNumberInThirdStopWithMoreValidations']),
            "transactionNumberInFourthStopWithMoreValidations": float(
                row['transactionNumberInFourthStopWithMoreValidations']),
            "transactionNumberInFifthStopWithMoreValidations": float(
                row['transactionNumberInFifthStopWithMoreValidations']),
            "transactionNumberInSixthStopWithMoreValidations": float(
                row['transactionNumberInSixthStopWithMoreValidations']),
            "transactionNumberInSeventhStopWithMoreValidations": float(
                row['transactionNumberInSeventhStopWithMoreValidations']),
            "transactionNumberInEighthStopWithMoreValidations": float(
                row['transactionNumberInEighthStopWithMoreValidations']),
            "transactionNumberInNinethStopWithMoreValidations": float(
                row['transactionNumberInNinethStopWithMoreValidations']),
            "transactionNumberInTenthStopWithMoreValidations": float(
                row['transactionNumberInTenthStopWithMoreValidations']),
            "firstBusStopWithMoreValidations": row['firstBusStopWithMoreValidations'],
            "secondBusStopWithMoreValidations": row['secondBusStopWithMoreValidations'],
            "thirdBusStopWithMoreValidations": row['thirdBusStopWithMoreValidations'],
            "fourthBusStopWithMoreValidations": row['fourthBusStopWithMoreValidations'],
            "fifthBusStopWithMoreValidations": row['fifthBusStopWithMoreValidations'],
            "sixthBusStopWithMoreValidations": row['sixthBusStopWithMoreValidations'],
            "seventhBusStopWithMoreValidations": row['seventhBusStopWithMoreValidations'],
            "eighthBusStopWithMoreValidations": row['eighthBusStopWithMoreValidations'],
            "ninethBusStopWithMoreValidations": row['ninethBusStopWithMoreValidations'],
            "tenthBusStopWithMoreValidations": row['tenthBusStopWithMoreValidations'],
            "transactionNumberInFirstBusStopWithMoreValidations": float(
                row['transactionNumberInFirstBusStopWithMoreValidations']),
            "transactionNumberInSecondBusStopWithMoreValidations": float(
                row['transactionNumberInSecondBusStopWithMoreValidations']),
            "transactionNumberInThirdBusStopWithMoreValidations": float(
                row['transactionNumberInThirdBusStopWithMoreValidations']),
            "transactionNumberInFourthBusStopWithMoreValidations": float(
                row['transactionNumberInFourthBusStopWithMoreValidations']),
            "transactionNumberInFifthBusStopWithMoreValidations": float(
                row['transactionNumberInFifthBusStopWithMoreValidations']),
            "transactionNumberInSixthBusStopWithMoreValidations": float(
                row['transactionNumberInSixthBusStopWithMoreValidations']),
            "transactionNumberInSeventhBusStopWithMoreValidations": float(
                row['transactionNumberInSeventhBusStopWithMoreValidations']),
            "transactionNumberInEighthBusStopWithMoreValidations": float(
                row['transactionNumberInEighthBusStopWithMoreValidations']),
            "transactionNumberInNinethBusStopWithMoreValidations": float(
                row['transactionNumberInNinethBusStopWithMoreValidations']),
            "transactionNumberInTenthBusStopWithMoreValidations": float(
                row['transactionNumberInTenthBusStopWithMoreValidations'])
        }
